# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='song',
            name='song_src',
            field=models.CharField(default=datetime.datetime(2018, 7, 31, 16, 13, 45, 156000, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
    ]
